language: java
jdk:
  - openjdk11
before_install:
  - chmod +x gradlew
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bren@juanantonio.info
script:
  - ./gradlew clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)
