/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jabrena' at '21/05/17 19:34' with Gradle 2.4
 *
 * @author jabrena, @date 21/05/17 19:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
